title: Rooted in Boston Event Series - a project of SPARK Boston
author: SPARK Boston 
email: sparkboston.gov
description: 
  Come learn more about SPARK Boston's Rooted in Boston event series, featuring various events that reimagine civic engagement.

# social links
twitter_username: sparkboston
github_username:  rootedinboston

show_excerpts: true # set to false to remove excerpts on the homepage
